"""Deterministic static facts used by future code-understanding insights."""

from pysynoptic.insights.analyze import (
    analyze_callable_insight,
    analyze_class_insight,
    analyze_insights,
    analyze_module_insight,
    build_insight_analysis,
)
from pysynoptic.insights.classify import classify_evidence
from pysynoptic.insights.confidence import assess_confidence
from pysynoptic.insights.evidence import (
    generate_callable_evidence,
    generate_class_evidence,
    generate_evidence,
    generate_module_evidence,
)
from pysynoptic.insights.facts import extract_module_facts, extract_project_facts
from pysynoptic.insights.flow_explanation import (
    FlowDecision,
    FlowException,
    FlowExplanation,
    FlowExplanationReliability,
    FlowLoop,
    FlowOutcome,
    FlowStep,
    analyze_flow_explanation,
    explain_callable_flow,
)
from pysynoptic.insights.models import (
    CallableFacts,
    CallableInsight,
    ClassFacts,
    ClassInsight,
    EvidenceCategory,
    EvidenceStrength,
    InsightAnalysis,
    InsightConfidence,
    InsightEvidence,
    InsightInput,
    InsightRole,
    ModuleFacts,
    ModuleInsight,
    ParameterFacts,
    PurposeResult,
    PurposeSource,
    RoleClassification,
    RoleSupport,
    StaticOperation,
)
from pysynoptic.insights.purpose import generate_purpose

__all__ = [
    "CallableFacts",
    "CallableInsight",
    "ClassFacts",
    "ClassInsight",
    "EvidenceCategory",
    "EvidenceStrength",
    "FlowDecision",
    "FlowException",
    "FlowExplanation",
    "FlowExplanationReliability",
    "FlowLoop",
    "FlowOutcome",
    "FlowStep",
    "InsightConfidence",
    "InsightEvidence",
    "InsightInput",
    "InsightAnalysis",
    "InsightRole",
    "ModuleFacts",
    "ModuleInsight",
    "ParameterFacts",
    "PurposeResult",
    "PurposeSource",
    "RoleClassification",
    "RoleSupport",
    "StaticOperation",
    "analyze_callable_insight",
    "analyze_flow_explanation",
    "analyze_class_insight",
    "analyze_insights",
    "analyze_module_insight",
    "assess_confidence",
    "build_insight_analysis",
    "classify_evidence",
    "extract_module_facts",
    "extract_project_facts",
    "explain_callable_flow",
    "generate_callable_evidence",
    "generate_class_evidence",
    "generate_evidence",
    "generate_module_evidence",
    "generate_purpose",
]
