"""Optional rewriting layer over deterministic static flow explanations."""

from pysynoptic.insights.ai_explanation.models import (
    AIExplanationDecision,
    AIExplanationException,
    AIExplanationLoop,
    AIExplanationOmissions,
    AIExplanationOutcome,
    AIExplanationRequest,
    AIExplanationResult,
    AIExplanationStep,
    AIProviderConfig,
    AIProviderKind,
    AIResolvedCallee,
)
from pysynoptic.insights.ai_explanation.providers import (
    MAX_HTTP_RESPONSE_BYTES,
    AIConfigurationError,
    AIExplanationDisabledError,
    AIExplanationError,
    AIExplanationProvider,
    AIProviderError,
    AIResponseError,
    DisabledAIExplanationProvider,
    JSONTransport,
    OllamaCompatibleProvider,
    OpenAICompatibleProvider,
    UrllibJSONTransport,
    is_local_endpoint,
    provider_from_config,
    validate_ai_text,
)
from pysynoptic.insights.ai_explanation.request import (
    MAX_AI_REQUEST_CHARS,
    SYSTEM_INSTRUCTION,
    build_ai_explanation_request,
    build_ai_prompt,
    normalize_ai_explanation_request,
    request_hash,
    request_payload,
)
from pysynoptic.insights.ai_explanation.service import (
    AIExplanationService,
    CachedAIExplanation,
    StaleAIExplanationError,
)

__all__ = [
    "AIConfigurationError",
    "AIExplanationDecision",
    "AIExplanationDisabledError",
    "AIExplanationError",
    "AIExplanationException",
    "AIExplanationLoop",
    "AIExplanationOmissions",
    "AIExplanationOutcome",
    "AIExplanationProvider",
    "AIExplanationRequest",
    "AIExplanationResult",
    "AIExplanationService",
    "AIExplanationStep",
    "AIProviderConfig",
    "AIProviderError",
    "AIProviderKind",
    "AIResolvedCallee",
    "AIResponseError",
    "CachedAIExplanation",
    "DisabledAIExplanationProvider",
    "JSONTransport",
    "MAX_AI_REQUEST_CHARS",
    "MAX_HTTP_RESPONSE_BYTES",
    "OllamaCompatibleProvider",
    "OpenAICompatibleProvider",
    "SYSTEM_INSTRUCTION",
    "StaleAIExplanationError",
    "UrllibJSONTransport",
    "build_ai_explanation_request",
    "build_ai_prompt",
    "is_local_endpoint",
    "normalize_ai_explanation_request",
    "provider_from_config",
    "request_hash",
    "request_payload",
    "validate_ai_text",
]
